In [40]:
!pip install pandas
!pip install matplotlib
!pip install numpy
!pip install seaborn
!pip install sklearn

Requirement already satisfied: pandas in /home/gitpod/.pyenv/versions/3.8.13/lib/python3.8/site-packages (1.4.3)
Requirement already satisfied: pytz>=2020.1 in /home/gitpod/.pyenv/versions/3.8.13/lib/python3.8/site-packages (from pandas) (2022.1)
Requirement already satisfied: numpy>=1.18.5 in /home/gitpod/.pyenv/versions/3.8.13/lib/python3.8/site-packages (from pandas) (1.23.1)
Requirement already satisfied: python-dateutil>=2.8.1 in /home/gitpod/.pyenv/versions/3.8.13/lib/python3.8/site-packages (from pandas) (2.8.2)
Requirement already satisfied: six>=1.5 in /home/gitpod/.pyenv/versions/3.8.13/lib/python3.8/site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)

[notice] A new release of pip available: 22.2 -> 22.2.2
[notice] To update, run: pip install --upgrade pip
Requirement already satisfied: matplotlib in /home/gitpod/.pyenv/versions/3.8.13/lib/python3.8/site-packages (3.5.2)
Requirement already satisfied: python-dateutil>=2.7 in /home/gitpod/.pyenv/versions/3.8.13/lib/python3.8/site-packages (from matplotlib) (2.8.2)
Requirement already satisfied: fonttools>=4.22.0 in /home/gitpod/.pyenv/versions/3.8.13/lib/python3.8/site-packages (from matplotlib) (4.34.4)
Requirement already satisfied: packaging>=20.0 in /home/gitpod/.pyenv/versions/3.8.13/lib/python3.8/site-packages (from matplotlib) (21.3)
Requirement already satisfied: pillow>=6.2.0 in /home/gitpod/.pyenv/versions/3.8.13/lib/python3.8/site-packages (from matplotlib) (9.2.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/gitpod/.pyenv/versions/3.8.13/lib/python3.8/site-packages (from matplotlib) (1.4.4)
Requirement already satisfied: numpy>=1.17 in /home/gitpod/.pyenv/versions/3.8.13/lib/python3.8/site-packages (from matplotlib) (1.23.1)
Requirement already satisfied: pyparsing>=2.2.1 in /home/gitpod/.pyenv/versions/3.8.13/lib/python3.8/site-packages (from matplotlib) (3.0.9)
Requirement already satisfied: cycler>=0.10 in /home/gitpod/.pyenv/versions/3.8.13/lib/python3.8/site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: six>=1.5 in /home/gitpod/.pyenv/versions/3.8.13/lib/python3.8/site-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)

[notice] A new release of pip available: 22.2 -> 22.2.2
[notice] To update, run: pip install --upgrade pip
Requirement already satisfied: numpy in /home/gitpod/.pyenv/versions/3.8.13/lib/python3.8/site-packages (1.23.1)

[notice] A new release of pip available: 22.2 -> 22.2.2
[notice] To update, run: pip install --upgrade pip
Requirement already satisfied: seaborn in /home/gitpod/.pyenv/versions/3.8.13/lib/python3.8/site-packages (0.11.2)
Requirement already satisfied: numpy>=1.15 in /home/gitpod/.pyenv/versions/3.8.13/lib/python3.8/site-packages (from seaborn) (1.23.1)
Requirement already satisfied: scipy>=1.0 in /home/gitpod/.pyenv/versions/3.8.13/lib/python3.8/site-packages (from seaborn) (1.9.0)
Requirement already satisfied: pandas>=0.23 in /home/gitpod/.pyenv/versions/3.8.13/lib/python3.8/site-packages (from seaborn) (1.4.3)
Requirement already satisfied: matplotlib>=2.2 in /home/gitpod/.pyenv/versions/3.8.13/lib/python3.8/site-packages (from seaborn) (3.5.2)
Requirement already satisfied: python-dateutil>=2.7 in /home/gitpod/.pyenv/versions/3.8.13/lib/python3.8/site-packages (from matplotlib>=2.2->seaborn) (2.8.2)
Requirement already satisfied: fonttools>=4.22.0 in /home/gitpod/.pyenv/versions/3.8.13/lib/python3.8/site-packages (from matplotlib>=2.2->seaborn) (4.34.4)
Requirement already satisfied: pyparsing>=2.2.1 in /home/gitpod/.pyenv/versions/3.8.13/lib/python3.8/site-packages (from matplotlib>=2.2->seaborn) (3.0.9)
Requirement already satisfied: pillow>=6.2.0 in /home/gitpod/.pyenv/versions/3.8.13/lib/python3.8/site-packages (from matplotlib>=2.2->seaborn) (9.2.0)
Requirement already satisfied: cycler>=0.10 in /home/gitpod/.pyenv/versions/3.8.13/lib/python3.8/site-packages (from matplotlib>=2.2->seaborn) (0.11.0)
Requirement already satisfied: packaging>=20.0 in /home/gitpod/.pyenv/versions/3.8.13/lib/python3.8/site-packages (from matplotlib>=2.2->seaborn) (21.3)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/gitpod/.pyenv/versions/3.8.13/lib/python3.8/site-packages (from matplotlib>=2.2->seaborn) (1.4.4)
Requirement already satisfied: pytz>=2020.1 in /home/gitpod/.pyenv/versions/3.8.13/lib/python3.8/site-packages (from pandas>=0.23->seaborn) (2022.1)
Requirement already satisfied: six>=1.5 in /home/gitpod/.pyenv/versions/3.8.13/lib/python3.8/site-packages (from python-dateutil>=2.7->matplotlib>=2.2->seaborn) (1.16.0)

[notice] A new release of pip available: 22.2 -> 22.2.2
[notice] To update, run: pip install --upgrade pip
Requirement already satisfied: pickle-mixin in /home/gitpod/.pyenv/versions/3.8.13/lib/python3.8/site-packages (1.0.2)

[notice] A new release of pip available: 22.2 -> 22.2.2
[notice] To update, run: pip install --upgrade pip
Collecting sklearn
  Using cached sklearn-0.0.tar.gz (1.1 kB)
  Preparing metadata (setup.py) ... done
Collecting scikit-learn
  Downloading scikit_learn-1.1.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (31.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 31.2/31.2 MB 19.2 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: numpy>=1.17.3 in /home/gitpod/.pyenv/versions/3.8.13/lib/python3.8/site-packages (from scikit-learn->sklearn) (1.23.1)
Requirement already satisfied: scipy>=1.3.2 in /home/gitpod/.pyenv/versions/3.8.13/lib/python3.8/site-packages (from scikit-learn->sklearn) (1.9.0)
Collecting joblib>=1.0.0
  Downloading joblib-1.1.0-py2.py3-none-any.whl (306 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 307.0/307.0 kB 64.7 MB/s eta 0:00:00
Collecting threadpoolctl>=2.0.0
  Downloading threadpoolctl-3.1.0-py3-none-any.whl (14 kB)
Building wheels for collected packages: sklearn
  Building wheel for sklearn (setup.py) ... done
  Created wheel for sklearn: filename=sklearn-0.0-py2.py3-none-any.whl size=1304 sha256=1507ea8946fb2dfb357bbdc75751a70b676558fbf2f8f15dc9ac82e699737dd5
  Stored in directory: /home/gitpod/.cache/pip/wheels/22/0b/40/fd3f795caaa1fb4c6cb738bc1f56100be1e57da95849bfc897
Successfully built sklearn
Installing collected packages: threadpoolctl, joblib, scikit-learn, sklearn
Successfully installed joblib-1.1.0 scikit-learn-1.1.1 sklearn-0.0 threadpoolctl-3.1.0

[notice] A new release of pip available: 22.2 -> 22.2.2
[notice] To update, run: pip install --upgrade pip

In [12]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [13]:
movies = pd.read_csv('../data/tmdb_5000_movies.csv')
credit_s = pd.read_csv('../data/tmdb_5000_credits.csv')

In [14]:
movies.sample(5)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
2182,0,"[{""id"": 16, ""name"": ""Animation""}, {""id"": 10751...",NaN,13682,[],en,Pooh's Heffalump Movie,Who or what exactly is a Heffalump? The lovabl...,9.031540,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2005-02-11,0,68.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,There's something new in the Hundred Acre Wood.,Pooh's Heffalump Movie,6.4,88
167,130000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",NaN,7364,"[{""id"": 168297, ""name"": ""tyrant""}, {""id"": 1683...",en,Sahara,Scouring the ocean depths for treasure-laden s...,21.605568,"[{""name"": ""Paramount Pictures"", ""id"": 4}, {""na...","[{""iso_3166_1"": ""DE"", ""name"": ""Germany""}, {""is...",2005-04-06,119269486,124.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Dirk Pitt. Adventure has a new name.,Sahara,5.7,434
4802,0,"[{""id"": 99, ""name"": ""Documentary""}]",NaN,25975,"[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...",en,My Date with Drew,Ever since the second grade when he first saw ...,1.929883,"[{""name"": ""rusty bear entertainment"", ""id"": 87...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2005-08-05,0,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,My Date with Drew,6.3,16
3151,10000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 35, ""nam...",http://www.gentlemenbroncos.com/,22820,"[{""id"": 1731, ""name"": ""writing""}, {""id"": 3548,...",en,Gentlemen Broncos,A teenager attends a fantasy writers' conventi...,3.193777,[],"[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-09-30,0,89.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Oinus, Ainous, Anous, Odious.",Gentlemen Broncos,6.2,51
1795,26000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",NaN,11509,"[{""id"": 798, ""name"": ""sheriff""}, {""id"": 1721, ...",en,Silverado,Four unwitting heroes cross paths on their jou...,10.981038,"[{""name"": ""Columbia Pictures"", ""id"": 5}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",1985-07-10,0,127.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Four strangers become friends. Four friends be...,Silverado,7.1,146

In [15]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4803 non-null   int64
 1   genres                4803 non-null   object
 2   homepage              1712 non-null   object
 3   id                    4803 non-null   int64
 4   keywords              4803 non-null   object
 5   original_language     4803 non-null   object
 6   original_title        4803 non-null   object
 7   overview              4800 non-null   object
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   object
 10  production_countries  4803 non-null   object
 11  release_date          4802 non-null   object
 12  revenue               4803 non-null   int64
 13  runtime               4801 non-null   float64
 14  spoken_languages      4803 non-null   object
 15  status                4803 non-null   object
 16  tagline               3959 non-null   object
 17  title                 4803 non-null   object
 18  vote_average          4803 non-null   float64
 19  vote_count            4803 non-null   int64
dtypes: float64(3), int64(4), object(13)
memory usage: 750.6+ KB

In [16]:
credit_s.sample(5)

,movie_id,title,cast,crew
829,11353,Bowfinger,"[{""cast_id"": 6, ""character"": ""Bobby Bowfinger""...","[{""credit_id"": ""52fe442c9251416c7502b705"", ""de..."
4714,282128,An American in Hollywood,"[{""cast_id"": 10, ""character"": ""Dorian"", ""credi...","[{""credit_id"": ""53cae343c3a36877610003df"", ""de..."
715,9334,The Scorpion King,"[{""cast_id"": 20, ""character"": ""Mathayus"", ""cre...","[{""credit_id"": ""536cb2dcc3a368122000b233"", ""de..."
3204,11588,The I Inside,"[{""cast_id"": 1, ""character"": ""Simon Cable"", ""c...","[{""credit_id"": ""52fe44619251416c75032aff"", ""de..."
16,24428,The Avengers,"[{""cast_id"": 46, ""character"": ""Tony Stark / Ir...","[{""credit_id"": ""52fe4495c3a368484e02b1cf"", ""de..."

In [17]:
credit_s.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  4803 non-null   int64
 1   title     4803 non-null   object
 2   cast      4803 non-null   object
 3   crew      4803 non-null   object
dtypes: int64(1), object(3)
memory usage: 150.2+ KB

In [18]:
movies = movies.merge(credit_s, on='title')

In [19]:
movies = movies[['movie_id','title','overview','genres','keywords','cast','crew']]

In [20]:
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [21]:

movies.dropna(inplace = True)

In [22]:
# genres that are included in the first row

movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [23]:
import ast

def convert(obj):
    L = []
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [24]:
# converting columns to obtain only the genres without a json format

movies['genres'] = movies['genres'].apply(convert)
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [25]:
movies['keywords'] = movies['keywords'].apply(convert)

In [26]:
#  function for the 'cast' column for converting

def convert3(obj):
    L = []
    count = 0
    for i in ast.literal_eval(obj):
        if count < 3:
            L.append(i['name'])
        count +=1  
    return L

In [27]:
movies['cast'] = movies['cast'].apply(convert3)

In [28]:
# how the dataset is coming along

movies.head(1)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [29]:
# From the crew we only obtain the the name of the director

def fetch_director(obj):
    L = []
    for i in ast.literal_eval(obj):
        if i['job'] == 'Director':
            L.append(i['name'])
            break
    return L

In [30]:
movies['crew'] = movies['crew'].apply(fetch_director)

In [31]:
# overview, convert it in a list by using 'split()' method

movies.overview[0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [32]:
movies['overview'] = movies['overview'].apply(lambda x : x.split())

In [33]:
# For the recommender system to do not get confused we will remove spaces between words

def collapse(L):
    L1 = []
    for i in L:
        L1.append(i.replace(" ",""))
    return L1

In [34]:
# apply function to the 'genres', 'cast', 'crew' and 'keywords' columns

movies['cast'] = movies['cast'].apply(collapse)
movies['crew'] = movies['crew'].apply(collapse)
movies['genres'] = movies['genres'].apply(collapse)
movies['keywords'] = movies['keywords'].apply(collapse)

In [35]:
# Reduction of the dataset by combining all our previous converted columns into only one column named 'tags'

movies['tags'] = movies['overview']+movies['genres']+movies['keywords']+movies['cast']+movies['crew']

In [36]:
pd.options.mode.chained_assignment = None  # default='warn'

new_df = movies[['movie_id','title','tags']]

new_df['tags'] = new_df['tags'].apply(lambda x :" ".join(x))

In [37]:
new_df['tags'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver JamesCameron'

In [38]:
new_df.to_csv('../data/processed/df_processed.csv')

## KNN algorithm

In [41]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000 ,stop_words='english')

In [ ]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [ ]:
vectors.shape

(4806, 5000)

In [ ]:
# 5000 most frequently used words

cv.get_feature_names()

/home/gitpod/.pyenv/versions/3.8.13/lib/python3.8/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

['000',
 '007',
 '10',
 '100',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '18th',
 '19',
 '1930s',
 '1940s',
 '1950',
 '1950s',
 '1960s',
 '1970s',
 '1980',
 '1980s',
 '1985',
 '1990s',
 '1999',
 '19th',
 '19thcentury',
 '20',
 '200',
 '2009',
 '20th',
 '24',
 '25',
 '30',
 '300',
 '3d',
 '40',
 '50',
 '500',
 '60',
 '60s',
 '70',
 '70s',
 'aaron',
 'aaroneckhart',
 'abandoned',
 'abducted',
 'abigailbreslin',
 'abilities',
 'ability',
 'able',
 'aboard',
 'abuse',
 'abusive',
 'academy',
 'accept',
 'accepted',
 'accepts',
 'access',
 'accident',
 'accidental',
 'accidentally',
 'accompanied',
 'accomplish',
 'account',
 'accountant',
 'accused',
 'ace',
 'achieve',
 'act',
 'acting',
 'action',
 'actionhero',
 'actions',
 'activist',
 'activities',
 'activity',
 'actor',
 'actors',
 'actress',
 'acts',
 'actual',
 'actually',
 'adam',
 'adams',
 'adamsandler',
 'adamshankman',
 'adaptation',
 'adapted',
 'addict',
 'addicted',
 'addiction',
 'adolescence',
 'adolescent',
 'adopt',
 'adopted',
 'adoption',
 'adopts',
 'adrienbrody',
 'adult',
 'adultanimation',
 'adultery',
 'adulthood',
 'adults',
 'advantage',
 'adventure',
 'adventures',
 'advertising',
 'advice',
 'affair',
 'affairs',
 'affection',
 'affections',
 'afghanistan',
 'africa',
 'african',
 'africanamerican',
 'aftercreditsstinger',
 'afterlife',
 'aftermath',
 'age',
 'aged',
 'agedifference',
 'agency',
 'agenda',
 'agent',
 'agents',
 'aggressive',
 'aging',
 'ago',
 'agree',
 'agrees',
 'ahead',
 'aid',
 'aided',
 'aids',
 'ailing',
 'air',
 'airplane',
 'airplanecrash',
 'airport',
 'aka',
 'al',
 'alabama',
 'alan',
 'alaska',
 'albert',
 'alcohol',
 'alcoholic',
 'alcoholism',
 'alecbaldwin',
 'alex',
 'alfredhitchcock',
 'ali',
 'alice',
 'alien',
 'alieninvasion',
 'alienlife',
 'aliens',
 'alike',
 'alive',
 'allen',
 'alliance',
 'allied',
 'allies',
 'allow',
 'allowing',
 'allows',
 'ally',
 'alongside',
 'alpacino',
 'alpha',
 'alter',
 'alternate',
 'alternative',
 'alzheimer',
 'amanda',
 'amandapeet',
 'amandaseyfried',
 'amateur',
 'amazing',
 'ambassador',
 'ambition',
 'ambitious',
 'ambulance',
 'ambush',
 'america',
 'american',
 'americanabroad',
 'americanfootball',
 'americans',
 'amid',
 'amidst',
 'amnesia',
 'amp',
 'amsterdam',
 'amusementpark',
 'amy',
 'amyadams',
 'amysmart',
 'ana',
 'anakin',
 'analyst',
 'anarchiccomedy',
 'ancient',
 'ancientrome',
 'ancientworld',
 'anderson',
 'andiemacdowell',
 'andrew',
 'android',
 'andy',
 'andygarcía',
 'angel',
 'angelabassett',
 'angeles',
 'angelinajolie',
 'angels',
 'anger',
 'anglee',
 'angry',
 'animal',
 'animalattack',
 'animalhorror',
 'animals',
 'animated',
 'animation',
 'anna',
 'annafaris',
 'anne',
 'annehathaway',
 'annemoss',
 'annettebening',
 'annie',
 'anniversary',
 'annual',
 'answer',
 'answers',
 'ant',
 'anthology',
 'anthony',
 'anthonyanderson',
 'anthonyhopkins',
 'anthropomorphism',
 'anti',
 'antics',
 'antihero',
 'antoinefuqua',
 'antoniobanderas',
 'antonyelchin',
 'apart',
 'apartheid',
 'apartment',
 'ape',
 'apes',
 'apocalypse',
 'apocalyptic',
 'apparent',
 'apparently',
 'appear',
 'appears',
 'apple',
 'appointed',
 'apprentice',
 'approach',
 'approaches',
 'approaching',
 'april',
 'aquarium',
 'arab',
 'arch',
 'archaeologist',
 'architect',
 'arctic',
 'area',
 'aren',
 'arena',
 'argument',
 'arise',
 'aristocrat',
 'armed',
 'arms',
 'army',
 'arnold',
 'arnoldschwarzenegger',
 'arrangedmarriage',
 'arrest',
 'arrested',
 'arrival',
 'arrive',
 'arrives',
 'arriving',
 'arrogant',
 'art',
 'arthur',
 'artificialintelligence',
 'artist',
 'artistic',
 'artists',
 'arts',
 'ashley',
 'ashleyjudd',
 'ashtonkutcher',
 'asia',
 'asian',
 'aside',
 'ask',
 'asked',
 'asking',
 'asks',
 'aspirations',
 'aspiring',
 'assassin',
 'assassinate',
 'assassination',
 'assassins',
 'assault',
 'assigned',
 'assignment',
 'assistant',
 'assumes',
 'asteroid',
 'astronaut',
 'astronauts',
 'asylum',
 'athlete',
 'atomicbomb',
 'attack',
 'attacked',
 'attacks',
 'attempt',
 'attempting',
 'attempts',
 'attending',
 'attends',
 'attention',
 'attitude',
 'attorney',
 'attracted',
 'attraction',
 'attractive',
 'audience',
 'audiences',
 'audition',
 'august',
 'aunt',
 'austin',
 'australia',
 'australian',
 'author',
 'authorities',
 'authority',
 'autism',
 'auto',
 'automobileracing',
 'avenge',
 'average',
 'avoid',
 'awaits',
 'awakens',
 'award',
 'away',
 'awry',
 'ax',
 'babe',
 'baby',
 'bachelor',
 'backdrop',
 'backed',
 'background',
 'backgrounds',
 'bad',
 'badly',
 'bag',
 'bahamas',
 'bail',
 'balance',
 'ball',
 'ballet',
 'baltimore',
 'band',
 'bandits',
 'bangkok',
 'banished',
 'bank',
 'banker',
 'bankrobber',
 'bankrobbery',
 'bar',
 'barely',
 'bargained',
 'barn',
 'barney',
 'barry',
 'barrylevinson',
 'bars',
 'base',
 'baseball',
 'based',
 'basedoncomicbook',
 'basedongraphicnovel',
 'basedonnovel',
 'basedonplay',
 'basedonstagemusical',
 'basedontrueevents',
 'basedontruestory',
 'basedontvseries',
 'basedonvideogame',
 'basedonyoungadultnovel',
 'basement',
 'basketball',
 'batman',
 'battle',
 'battlefield',
 'battles',
 'battling',
 'bay',
 'beach',
 'bear',
 'bears',
 'beast',
 'beasts',
 'beat',
 'beating',
 'beautiful',
 'beautifulwoman',
 'beauty',
 'becky',
 'becominganadult',
 'bed',
 'bedroom',
 'beer',
 'befriends',
 'began',
 'begin',
 'beginning',
 'begins',
 'behavior',
 'beings',
 'beliefs',
 'believe',
 'believed',
 'believes',
 'believing',
 'beloved',
 'ben',
 'benaffleck',
 'beneath',
 'benfoster',
 'beniciodeltoro',
 'benjamin',
 'benjaminbratt',
 'benkingsley',
 'bennett',
 'benstiller',
 'bent',
 'berlin',
 'best',
 'bestfriend',
 'bestfriendsinlove',
 'bet',
 'beth',
 'betrayal',
 'betrayed',
 'bettemidler',
 'better',
 'betty',
 'beverly',
 'bible',
 'big',
 'bigger',
 'biggest',
 'biker',
 'bikini',
 'billhader',
 'billionaire',
 'billmurray',
 'billnighy',
 'billpaxton',
 'billpullman',
 'billy',
 'billybobthornton',
 'billycrudup',
 'billycrystal',
 'biography',
 'bird',
 'birth',
 'birthday',
 'bisexual',
 'bishop',
 'bit',
 'bite',
 'bitter',
 'bizarre',
 'black',
 'blackmagic',
 'blackmail',
 'blackpeople',
 'blacksmith',
 'blade',
 'blame',
 'blind',
 'bliss',
 'block',
 'blonde',
 'blood',
 'bloodsplatter',
 'bloodthirsty',
 'bloody',
 'blow',
 'blue',
 'board',
 'boarding',
 'boardingschool',
 'boat',
 'bob',
 'bobby',
 'bobbyfarrelly',
 'bobhoskins',
 'bodies',
 'body',
 'bodyguard',
 'bold',
 'bollywood',
 'bomb',
 'bombing',
 'bond',
 'bonds',
 'bone',
 'book',
 'books',
 'border',
 'bored',
 'boredom',
 'boring',
 'born',
 'boss',
 'boston',
 'botched',
 'bound',
 'boundaries',
 'bounty',
 'bountyhunter',
 'bourne',
 'box',
 'boxer',
 'boxing',
 'boy',
 'boyfriend',
 'boys',
 'bradleycooper',
 'bradpitt',
 'brain',
 'brand',
 'brave',
 'bravery',
 'brazil',
 'brazilian',
 'break',
 'breakdown',
 'breaking',
 'breaks',
 'brendanfraser',
 'brendangleeson',
 'brent',
 'brettratner',
 'brian',
 'briandepalma',
 'bride',
 'bridesmaid',
 'bridge',
 'brief',
 'brielarson',
 'brien',
 'bright',
 'brilliant',
 'bring',
 'bringing',
 'brings',
 'brink',
 'britain',
 'british',
 'britishsecretservice',
 'brittanymurphy',
 'broadway',
 'broke',
 'broken',
 'broker',
 'bronx',
 'brooklyn',
 'brooks',
 'broom',
 'brothel',
 'brother',
 'brotherbrotherrelationship',
 'brothers',
 'brothersisterrelationship',
 'brought',
 'brown',
 'bruce',
 'brucegreenwood',
 'brucewillis',
 'brutal',
 'brutality',
 'brutally',
 'bryansinger',
 'buck',
 'buddies',
 'buddy',
 'buddycomedy',
 'budget',
 'build',
 'building',
 'built',
 'bully',
 'bullying',
 'bumbling',
 'bunny',
 'burglar',
 'buried',
 'bus',
 'bush',
 'business',
 'businessman',
 'bust',
 'busy',
 'butcher',
 'butler',
 'buy',
 'cabin',
 'caesar',
 'cage',
 'cairo',
 'cal',
 'california',
 'called',
 'calls',
 'calvin',
 'camcorder',
 'came',
 'camera',
 'cameraman',
 'cameras',
 'camerondiaz',
 'camp',
 'campaign',
 'campbell',
 'camping',
 'campus',
 'canada',
 'canadian',
 'cancer',
 'candidate',
 'candy',
 'cannibal',
 'capable',
 'capital',
 'capitalism',
 'capt',
 'captain',
 'captive',
 'capture',
 'captured',
 'captures',
 'car',
 'caraccident',
 'carchase',
 'carcrash',
 'card',
 'care',
 'career',
 'carefree',
 'caretaker',
 'caribbean',
 'carjourney',
 'carl',
 'carlagugino',
 'carmen',
 'carol',
 'carolina',
 'carrace',
 'carrie',
 'carry',
 'carrying',
 'cars',
 'cartel',
 'carter',
 'cartoon',
 'caryelwes',
 'case',
 'caseyaffleck',
 'cash',
 'casino',
 'cast',
 'castle',
 'cat',
 'cataclysm',
 'catastrophe',
 'catch',
 'catches',
 'cateblanchett',
 'catherinedeneuve',
 'catherinekeener',
 'catherinezeta',
 'catholic',
 'catholicism',
 'cattle',
 'caught',
 'cause',
 'caused',
 'causes',
 'causing',
 'cavalry',
 'cave',
 'cavemen',
 'celebrate',
 'celebrated',
 'celebration',
 'celebrity',
 'cellphone',
 'cemetery',
 'center',
 'centered',
 'centers',
 'central',
 'centuries',
 'century',
 'ceremony',
 'certain',
 'chain',
 'chainsaw',
 'challenge',
 'challenged',
 'challenges',
 'champion',
 'championship',
 'chance',
 'change',
 'changed',
 'changes',
 'changing',
 'channingtatum',
 'chaos',
 'chaotic',
 'chapter',
 'character',
 'characters',
 'charge',
 'charged',
 'charismatic',
 'charles',
 'charlie',
 'charliesheen',
 'charlizetheron',
 'charlotte',
 'charm',
 'charming',
 'chase',
 'chased',
 'chases',
 'chauffeur',
 'chazzpalminteri',
 'cheating',
 'cheerleader',
 'chef',
 'chemical',
 'cher',
 'chicago',
 'chicken',
 'chief',
 'child',
 'childabuse',
 'childhero',
 'childhood',
 'children',
 'chilling',
 'china',
 'chinese',
 'chip',
 'chiwetelejiofor',
 'chloëgracemoretz',
 'chloësevigny',
 'chocolate',
 'choice',
 'choices',
 'choose',
 'chosen',
 'chowyun',
 'chris',
 'chriscolumbus',
 'chriscooper',
 'chrisevans',
 'chrishemsworth',
 'chrisklein',
 'chrispine',
 'chrisrock',
 'christ',
 'christian',
 'christianbale',
 'christianity',
 'christianslater',
 'christinaapplegate',
 'christinaricci',
 'christine',
 'christmas',
 'christmasparty',
 'christopher',
 'christopherlloyd',
 'christophernolan',
 'christopherplummer',
 'christopherwalken',
 'christophwaltz',
 'chrisweitz',
 'chronicle',
 'chronicles',
 'chuck',
 'church',
 'cia',
 'cigarettesmoking',
 'cillianmurphy',
 'cindy',
 'cinema',
 'circle',
 'circuit',
 'circumstances',
 'circus',
 'cities',
 'citizens',
 'city',
 'civil',
 'civilian',
 'civilization',
 'civilwar',
 'claim',
 'claims',
 'claire',
 'clairedanes',
 'clan',
 'clark',
 'clash',
 'class',
 'classes',
 'classic',
 'classmate',
 'classmates',
 'classroom',
 'claudevandamme',
 'clay',
 'clean',
 'clear',
 'clerk',
 'client',
 'clients',
 'climate',
 'climbing',
 'clinteastwood',
 'clique',
 'cliveowen',
 'clock',
 'clone',
 'cloning',
 'close',
 'closed',
 'closer',
 'club',
 'clubs',
 'clues',
 'clutches',
 'coach',
 'coast',
 'cocaine',
 'code',
 'cody',
 'coffin',
 'cohen',
 'col',
 'cold',
 'coldwar',
 'cole',
 'colin',
 'colinfarrell',
 'colinfirth',
 'collapse',
 'colleague',
 'colleagues',
 'collect',
 'collection',
 'collector',
 'college',
 'collide',
 'collision',
 'colonel',
 'colony',
 'color',
 'colorado',
 'colorful',
 'coma',
 'combat',
 'combined',
 'come',
 'comeback',
 'comedian',
 'comedic',
 'comedy',
 'comes',
 'comet',
 'comfort',
 'comic',
 'comics',
 'coming',
 'comingofage',
 'comingout',
 'command',
 'commander',
 'commercial',
 'commit',
 'commitment',
 'committed',
 'common',
 'communication',
 'community',
 'companion',
 'company',
 'compete',
 'competing',
 'competition',
 'complete',
 'completely',
 'complex',
 'complicated',
 'complications',
 'composer',
 'computer',
 'computervirus',
 'conan',
 'concert',
 'conclusion',
 'condition',
 'confederate',
 'confession',
 'confidence',
 'confident',
 'conflict',
 'confront',
 'confronted',
 'confronts',
 'confused',
 'congress',
 'conman',
 'connected',
 'connection',
 'connell',
 'connor',
 'conquer',
 'conscience',
 'consequences',
 'conservative',
 'considered',
 'conspiracy',
 'conspire',
 'constant',
 'constantly',
 'construction',
 'consumed',
 'contact',
 'contain',
 'contemporary',
 'contend',
 'contest',
 'continue',
 'continues',
 'continuing',
 'contract',
 'control',
 'controlled',
 'controlling',
 'controversial',
 'convention',
 'converge',
 'convict',
 'convicted',
 'convince',
 'convinced',
 'convinces',
 'cook',
 'cooking',
 'cool',
 'cooper',
 'cop',
 'cope',
 'cops',
 'core',
 'corner',
 'corners',
 'corporate',
 'corporation',
 'corpse',
 'corrupt',
 'corruption',
 'cost',
 ...]

In [ ]:
# find the cosine_similarity among the movies

from sklearn.metrics.pairwise import cosine_similarity
cosine_similarity(vectors).shape

(4806, 4806)

In [ ]:
similarity = cosine_similarity(vectors)
similarity[0]

array([1.        , 0.08964215, 0.05976143, ..., 0.02519763, 0.02817181,
       0.        ])

In [ ]:
sorted(list(enumerate(similarity[0])),reverse =True , key = lambda x:x[1])[1:6]

[(539, 0.26089696604360174),
 (1194, 0.2581988897471611),
 (507, 0.25302403842552984),
 (260, 0.25110592822973776),
 (1216, 0.24944382578492943)]

In [ ]:
# recommendation function based on the cosine_similarity

def recommend(movie):
    movie_index = new_df[new_df['title'] == movie].index[0] ##fetching the movie index
    distances = similarity[movie_index]
    movie_list = sorted(list(enumerate( distances)),reverse =True , key = lambda x:x[1])[1:6]
    
    for i in movie_list:
        print(new_df.iloc[i[0]].title)

In [ ]:
new_df.sample(10)

,movie_id,title,tags
929,6950,Outbreak,A deadly airborne virus finds its way into the...
2092,772,Home Alone 2: Lost in New York,"Instead of flying to Florida with his folks, K..."
530,37821,Killers,When an elite assassin marries a beautiful com...
3727,362105,R.L. Stine's Monsterville: The Cabinet of Souls,Teenage friends must resist the spell of an ev...
3476,57612,Dolphins and Whales: Tribes of the Ocean,This documentary goes to coral reefs of the Ba...
2254,14652,Bon voyage,Isabelle Adjani and Gerard Depardieu star in d...
1106,5503,The Fugitive,"Wrongfully accused of murdering his wife, Rich..."
3909,10225,Friday the 13th Part VI: Jason Lives,"As a child, Tommy killed mass-murderer Jason. ..."
4573,15624,Conversations with Other Women,"Reunited at a wedding after many years, former..."
3823,25209,Annie Get Your Gun,This film adaptation of Irving Berlin's classi...

In [ ]:
# Trying the model out

In [ ]:
recommend('Home Alone 2: Lost in New York')

Home Alone
Christmas with the Kranks
A Charlie Brown Christmas
Bad Santa
Love the Coopers

In [ ]:
recommend('The Dark Knight Rises')

The Dark Knight
Batman Begins
Batman
Batman Returns
Batman

In [ ]:
recommend('The Twilight Saga: Eclipse')

The Twilight Saga: New Moon
The Twilight Saga: Breaking Dawn - Part 2
Twilight
Underworld: Awakening
Underworld

In [ ]:
recommend('Pretty Woman')

Crocodile Dundee
Alvin and the Chipmunks: The Road Chip
Kangaroo Jack
The Out-of-Towners
30 Minutes or Less

In [ ]:
recommend('Megamind')

The Helix... Loaded
Superhero Movie
Up
Alvin and the Chipmunks: The Road Chip
The Toxic Avenger